// (C) Aleksandr Dikarev, 2015

#ifndef _TAL_PINS_H_
#define _TAL_PINS_H_

// STM32F429Vx

#include <stm32f4xx.h>
#define USART1_DR_ADDRESS             ((unsigned int)USART1 + 0x04)
#define USART2_DR_ADDRESS             ((unsigned int)USART2 + 0x04)
#define USART3_DR_ADDRESS             ((unsigned int)USART3 + 0x04)
#define UART4_DR_ADDRESS              ((unsigned int)UART4 + 0x04)
#define UART5_DR_ADDRESS              ((unsigned int)UART5 + 0x04)
#define USART6_DR_ADDRESS             ((unsigned int)USART6 + 0x04)
#define UART7_DR_ADDRESS              ((unsigned int)UART7 + 0x04)
#define UART8_DR_ADDRESS              ((unsigned int)UART8 + 0x04)

typedef enum
{
	TAL_RCC_BUS_ID_AHB1 = 0,
	TAL_RCC_BUS_ID_AHB2 = 1,
	TAL_RCC_BUS_ID_AHB3 = 2,
	TAL_RCC_BUS_ID_APB1 = 3,
	TAL_RCC_BUS_ID_APB2 = 4,
	TAL_RCC_BUS_ID_INVALID
} TAL_RCC_BUS_ID_ENUM;
#define IS_RCC_BUS_ID(value) ((value >= RCC_BUS_ID_AHB1) && (value < RCC_BUS_ID_INVALID))

// WATCHDOG
#define TAL_IWDG_PRESCALER            (IWDG_Prescaler_64)

// TICK TIMER
#define TAL_SYS_CLK_FREQ              (168000000)
#define TAL_TICK_TIMER_FREQ           (10000)
#define TAL_TICKS_PER_MS              (TAL_TICK_TIMER_FREQ / 2000)
#define TAL_TICK_TIMER                (TIM5)
#define TAL_TICK_TIMER_PRESCALER      (TAL_SYS_CLK_FREQ / TAL_TICK_TIMER_FREQ)
#define TAL_TICK_TIMER_RCC            (RCC_APB1Periph_TIM5)
#define TAL_TICK_TIMER_BUS_ID         (TAL_RCC_BUS_ID_APB1)


// USARTs alternative pin configuation
#define TAL_DC1_PINS_CONFIG           (1)
#define TAL_DC2_PINS_CONFIG           (0)
#define TAL_DC3_PINS_CONFIG           (1)
#define TAL_DC4_PINS_CONFIG           (0)

// Data channel 1 (USART1)
#define TAL_DC1_USART_ID              (USART1)
#define TAL_DC1_DR_ADDRESS            (USART1_DR_ADDRESS)
#define TAL_DC1_RCC                   (RCC_APB2Periph_USART1)
#define TAL_DC1_BUS_ID                (TAL_RCC_BUS_ID_APB2)
#if (TAL_DC1_PINS_CONFIG == 0)
#define TAL_DC1_TX_GPIO_PORT          (GPIOA)
#define TAL_DC1_TX_GPIO_PIN           (GPIO_Pin_9)
#define TAL_DC1_TX_PINSOURCE          (GPIO_PinSource9)
#define TAL_DC1_RX_GPIO_PORT          (GPIOA)
#define TAL_DC1_RX_GPIO_PIN           (GPIO_Pin_10)
#define TAL_DC1_RX_PINSOURCE          (GPIO_PinSource10)
#define TAL_DC1_PINS_RCC              (RCC_AHB1Periph_GPIOA)
#define TAL_DC1_PINS_BUS_ID           (TAL_RCC_BUS_ID_AHB1)
#else
#define TAL_DC1_TX_GPIO_PORT          (GPIOB)
#define TAL_DC1_TX_GPIO_PIN           (GPIO_Pin_6)
#define TAL_DC1_TX_PINSOURCE          (GPIO_PinSource6)
#define TAL_DC1_RX_GPIO_PORT          (GPIOB)
#define TAL_DC1_RX_GPIO_PIN           (GPIO_Pin_7)
#define TAL_DC1_RX_PINSOURCE          (GPIO_PinSource7)
#define TAL_DC1_PINS_RCC              (RCC_AHB1Periph_GPIOB)
#define TAL_DC1_PINS_BUS_ID           (TAL_RCC_BUS_ID_AHB1)
#endif
#define TAL_DC1_GPIO_AF               (GPIO_AF_USART1)
#define TAL_DC1_USART_IT_RXNE         (USART_IT_RXNE)
#define TAL_DC1_TX_DMA_RCC            (RCC_AHB1Periph_DMA2)
#define TAL_DC1_TX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC1_TX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC1_TX_DMA_STREAM         (DMA2_Stream7)
#define TAL_DC1_TX_DMA_IRQ            (DMA2_Stream7_IRQn)
#define TAL_DC1_RX_DMA_RCC            (RCC_AHB1Periph_DMA2)
#define TAL_DC1_RX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC1_RX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC1_RX_DMA_STREAM         (DMA2_Stream2)
#define TAL_DC1_RX_DMA_IRQ            (DMA2_Stream2_IRQn)
#define TAL_DC1_RX_IRQ                (USART1_IRQn)

// Data channel 2 (USART2)
#define TAL_DC2_USART_ID              (USART2)
#define TAL_DC2_DR_ADDRESS            (USART2_DR_ADDRESS)
#define TAL_DC2_RCC                   (RCC_APB1Periph_USART2)
#define TAL_DC2_BUS_ID                (TAL_RCC_BUS_ID_APB1)
#if (TAL_DC2_PINS_CONFIG == 0)
#define TAL_DC2_TX_GPIO_PORT          (GPIOA)
#define TAL_DC2_TX_GPIO_PIN           (GPIO_Pin_2)
#define TAL_DC2_TX_PINSOURCE          (GPIO_PinSource2)
#define TAL_DC2_RX_GPIO_PORT          (GPIOA)
#define TAL_DC2_RX_GPIO_PIN           (GPIO_Pin_3)
#define TAL_DC2_RX_PINSOURCE          (GPIO_PinSource3)
#define TAL_DC2_PINS_RCC              (RCC_AHB1Periph_GPIOA)
#define TAL_DC2_PINS_BUS_ID           (TAL_RCC_BUS_ID_AHB1)
#else
#define TAL_DC2_TX_GPIO_PORT          (GPIOD)
#define TAL_DC2_TX_GPIO_PIN           (GPIO_Pin_5)
#define TAL_DC2_TX_PINSOURCE          (GPIO_PinSource5)
#define TAL_DC2_RX_GPIO_PORT          (GPIOD)
#define TAL_DC2_RX_GPIO_PIN           (GPIO_Pin_6)
#define TAL_DC2_RX_PINSOURCE          (GPIO_PinSource6)
#define TAL_DC2_PINS_RCC              (RCC_AHB1Periph_GPIOD)
#define TAL_DC2_PINS_BUS_ID           (TAL_RCC_BUS_ID_AHB1)
#endif
#define TAL_DC2_GPIO_AF               (GPIO_AF_USART2)
#define TAL_DC2_USART_IT_RXNE         (USART_IT_RXNE)
#define TAL_DC2_TX_DMA_RCC            (RCC_AHB1Periph_DMA1)
#define TAL_DC2_TX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC2_TX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC2_TX_DMA_STREAM         (DMA1_Stream6)
#define TAL_DC2_TX_DMA_IRQ            (DMA1_Stream6_IRQn)
#define TAL_DC2_RX_DMA_RCC            (RCC_AHB1Periph_DMA1)
#define TAL_DC2_RX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC2_RX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC2_RX_DMA_STREAM         (DMA1_Stream5)
#define TAL_DC2_RX_DMA_IRQ            (DMA1_Stream5_IRQn)
#define TAL_DC2_RX_IRQ                (USART2_IRQn)

// Data channel 3 (USART3)
#define TAL_DC3_USART_ID              (USART3)
#define TAL_DC3_DR_ADDRESS            (USART3_DR_ADDRESS)
#define TAL_DC3_RCC                   (RCC_APB1Periph_USART3)
#define TAL_DC3_BUS_ID                (TAL_RCC_BUS_ID_APB1)
#if (TAL_DC3_PINS_CONFIG == 0)
#define TAL_DC3_TX_GPIO_PORT          (GPIOB)
#define TAL_DC3_TX_GPIO_PIN           (GPIO_Pin_10)
#define TAL_DC3_TX_PINSOURCE          (GPIO_PinSource10)
#define TAL_DC3_RX_GPIO_PORT          (GPIOB)
#define TAL_DC3_RX_GPIO_PIN           (GPIO_Pin_11)
#define TAL_DC3_RX_PINSOURCE          (GPIO_PinSource11)
#define TAL_DC3_PINS_RCC              (RCC_AHB1Periph_GPIOB)
#define TAL_DC3_PINS_BUS_ID           (TAL_RCC_BUS_ID_AHB1)
#elif (TAL_DC3_PINS_CONFIG == 1)
#define TAL_DC3_TX_GPIO_PORT            (GPIOD)
#define TAL_DC3_TX_GPIO_PIN             (GPIO_Pin_8)
#define TAL_DC3_TX_PINSOURCE            (GPIO_PinSource8)
#define TAL_DC3_RX_GPIO_PORT            (GPIOD)
#define TAL_DC3_RX_GPIO_PIN             (GPIO_Pin_9)
#define TAL_DC3_RX_PINSOURCE            (GPIO_PinSource9)
#define TAL_DC3_PINS_RCC                (RCC_AHB1Periph_GPIOD)
#define TAL_DC3_PINS_BUS_ID             (TAL_RCC_BUS_ID_AHB1)
#else
#define TAL_DC3_TX_GPIO_PORT            (GPIOC)
#define TAL_DC3_TX_GPIO_PIN             (GPIO_Pin_10)
#define TAL_DC3_TX_PINSOURCE            (GPIO_PinSource10)
#define TAL_DC3_RX_GPIO_PORT            (GPIOC)
#define TAL_DC3_RX_GPIO_PIN             (GPIO_Pin_11)
#define TAL_DC3_RX_PINSOURCE            (GPIO_PinSource11)
#define TAL_DC3_PINS_RCC                (RCC_AHB1Periph_GPIOC)
#define TAL_DC3_PINS_BUS_ID             (TAL_RCC_BUS_ID_AHB1)
#endif
#define TAL_DC3_GPIO_AF               (GPIO_AF_USART3)
#define TAL_DC3_USART_IT_RXNE         (USART_IT_RXNE)
#define TAL_DC3_TX_DMA_RCC            (RCC_AHB1Periph_DMA1)
#define TAL_DC3_TX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC3_TX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC3_TX_DMA_STREAM         (DMA1_Stream3)
#define TAL_DC3_TX_DMA_IRQ            (DMA1_Stream3_IRQn)
#define TAL_DC3_RX_DMA_RCC            (RCC_AHB1Periph_DMA1)
#define TAL_DC3_RX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC3_RX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC3_RX_DMA_STREAM         (DMA1_Stream1)
#define TAL_DC3_RX_DMA_IRQ            (DMA1_Stream1_IRQn)
#define TAL_DC3_RX_IRQ                (USART3_IRQn)

// Data channel 4 (UART4)
#define TAL_DC4_USART_ID              (UART4)
#define TAL_DC4_DR_ADDRESS            (UART4_DR_ADDRESS)
#define TAL_DC4_RCC                   (RCC_APB1Periph_UART4)
#define TAL_DC4_BUS_ID                (TAL_RCC_BUS_ID_APB1)
#if (TAL_DC4_PINS_CONFIG == 0)
#define TAL_DC4_TX_GPIO_PORT          (GPIOA)
#define TAL_DC4_TX_GPIO_PIN           (GPIO_Pin_0)
#define TAL_DC4_TX_PINSOURCE          (GPIO_PinSource0)
#define TAL_DC4_RX_GPIO_PORT          (GPIOA)
#define TAL_DC4_RX_GPIO_PIN           (GPIO_Pin_1)
#define TAL_DC4_RX_PINSOURCE          (GPIO_PinSource1)
#define TAL_DC4_PINS_RCC              (RCC_AHB1Periph_GPIOA)
#define TAL_DC4_PINS_BUS_ID           (TAL_RCC_BUS_ID_AHB1)
#else
#define TAL_DC4_TX_GPIO_PORT            (GPIOC)
#define TAL_DC4_TX_GPIO_PIN             (GPIO_Pin_10)
#define TAL_DC4_TX_PINSOURCE            (GPIO_PinSource10)
#define TAL_DC4_RX_GPIO_PORT            (GPIOC)
#define TAL_DC4_RX_GPIO_PIN             (GPIO_Pin_11)
#define TAL_DC4_RX_PINSOURCE            (GPIO_PinSource11)
#define TAL_DC4_PINS_RCC                (RCC_AHB1Periph_GPIOC)
#define TAL_DC4_PINS_BUS_ID             (TAL_RCC_BUS_ID_AHB1)
#endif
#define TAL_DC4_GPIO_AF               (GPIO_AF_UART4)
#define TAL_DC4_USART_IT_RXNE         (USART_IT_RXNE)
#define TAL_DC4_TX_DMA_RCC            (RCC_AHB1Periph_DMA1)
#define TAL_DC4_TX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC4_TX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC4_TX_DMA_STREAM         (DMA1_Stream4)
#define TAL_DC4_TX_DMA_IRQ            (DMA1_Stream4_IRQn)
#define TAL_DC4_RX_DMA_RCC            (RCC_AHB1Periph_DMA1)
#define TAL_DC4_RX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC4_RX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC4_RX_DMA_STREAM         (DMA1_Stream2)
#define TAL_DC4_RX_DMA_IRQ            (DMA1_Stream2_IRQn)
#define TAL_DC4_RX_IRQ                (UART4_IRQn)

// Data channel 5 (UART5)
#define TAL_DC5_USART_ID              (UART5)
#define TAL_DC5_DR_ADDRESS            (UART5_DR_ADDRESS)
#define TAL_DC5_RCC                   (RCC_APB1Periph_UART5)
#define TAL_DC5_BUS_ID                (TAL_RCC_BUS_ID_APB1)
#define TAL_DC5_TX_GPIO_PORT          (GPIOC)
#define TAL_DC5_TX_GPIO_PIN           (GPIO_Pin_12)
#define TAL_DC5_TX_PINSOURCE          (GPIO_PinSource12)
#define TAL_DC5_RX_GPIO_PORT          (GPIOD)
#define TAL_DC5_RX_GPIO_PIN           (GPIO_Pin_2)
#define TAL_DC5_RX_PINSOURCE          (GPIO_PinSource2)
#define TAL_DC5_PINS_RCC              (RCC_AHB1Periph_GPIOC | RCC_AHB1Periph_GPIOD)
#define TAL_DC5_PINS_BUS_ID           (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC5_GPIO_AF               (GPIO_AF_UART5)
#define TAL_DC5_USART_IT_RXNE         (USART_IT_RXNE)
#define TAL_DC5_TX_DMA_RCC            (RCC_AHB1Periph_DMA1)
#define TAL_DC5_TX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC5_TX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC5_TX_DMA_STREAM         (DMA1_Stream0)
#define TAL_DC5_TX_DMA_IRQ            (DMA1_Stream0_IRQn)
#define TAL_DC5_RX_DMA_RCC            (RCC_AHB1Periph_DMA1)
#define TAL_DC5_RX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC5_RX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC5_RX_DMA_STREAM         (DMA1_Stream7)
#define TAL_DC5_RX_DMA_IRQ            (DMA1_Stream7_IRQn)
#define TAL_DC5_RX_IRQ                (UART5_IRQn)

// Data channel 6 (USART6)
#define TAL_DC6_USART_ID              (USART6)
#define TAL_DC6_DR_ADDRESS            (USART6_DR_ADDRESS)
#define TAL_DC6_RCC                   (RCC_APB2Periph_USART6)
#define TAL_DC6_BUS_ID                (TAL_RCC_BUS_ID_APB2)
#define TAL_DC6_TX_GPIO_PORT          (GPIOC)
#define TAL_DC6_TX_GPIO_PIN           (GPIO_Pin_6)
#define TAL_DC6_TX_PINSOURCE          (GPIO_PinSource6)
#define TAL_DC6_RX_GPIO_PORT          (GPIOC)
#define TAL_DC6_RX_GPIO_PIN           (GPIO_Pin_7)
#define TAL_DC6_RX_PINSOURCE          (GPIO_PinSource7)
#define TAL_DC6_PINS_RCC              (RCC_AHB1Periph_GPIOC)
#define TAL_DC6_PINS_BUS_ID           (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC6_GPIO_AF               (GPIO_AF_USART6)
#define TAL_DC6_USART_IT_RXNE         (USART_IT_RXNE)
#define TAL_DC6_TX_DMA_RCC            (RCC_AHB1Periph_DMA2)
#define TAL_DC6_TX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC6_TX_DMA_CHANNEL        (DMA_Channel_5)
#define TAL_DC6_TX_DMA_STREAM         (DMA2_Stream6)
#define TAL_DC6_TX_DMA_IRQ            (DMA2_Stream6_IRQn)
#define TAL_DC6_RX_DMA_RCC            (RCC_AHB1Periph_DMA1)
#define TAL_DC6_RX_DMA_BUS_ID         (TAL_RCC_BUS_ID_AHB1)
#define TAL_DC6_RX_DMA_CHANNEL        (DMA_Channel_4)
#define TAL_DC6_RX_DMA_STREAM         (DMA2_Stream5)
#define TAL_DC6_RX_DMA_IRQ            (DMA2_Stream5_IRQn)
#define TAL_DC6_RX_IRQ                (USART6_IRQn)

#endif
